e_voting/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from django.conf.urls.static import static
from django.conf import settings
from myapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include("myapp.urls")),
    path('',views.index,name="home"),
    path('logout/',views.user_logout,name="user_logout"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views

app_name="myapp"

urlpatterns = [
    path('register/',views.register,name="registration"),
    path('login/',views.user_login,name="login"),
    path('cast_vote/',views.cast_vote,name="cast_vote"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Constituency(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name
    

class Candidate(models.Model):
    name=models.CharField(max_length=50)
    constituency=models.ForeignKey(Constituency,on_delete=models.CASCADE)
    no_votes=models.IntegerField(default=0)

    def __str__(self):
        return self.name
    

class Voter(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    is_voted=models.BooleanField(default=False)
    constituency=models.ForeignKey(Constituency,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

myapp/forms.py
from django import forms
from myapp.models import *

class UserForm(forms.ModelForm):
    password=forms.CharField(max_length=20,widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=('username','email','password')


class VoterForm(forms.ModelForm):
    class Meta:
        model=Voter
        fields=('constituency',)

class ConstForm(forms.ModelForm):
    class Meta:
        model=Constituency
        fields="__all__"

myapp/views.py
from django.shortcuts import render
from myapp.forms import *
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

def index(request):
    user = request.user
    if user.is_authenticated:
        username = user.username.title()
        return render(request,"myapp/home.html",context={"username":username})
    return render(request,"myapp/home.html")

@login_required(login_url="/myapp/login")
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required(login_url="/myapp/login")
def cast_vote(request):
    user=request.user
    u=User.objects.get(username=user)
    if request.method=="POST":
        candidate_name=request.POST['cand_name']
        c=Candidate.objects.get(name=candidate_name)
        v=c.no_votes+1
        c=Candidate.objects.filter(name=candidate_name).update(no_votes=v)
        c=Voter.objects.filter(user=u).update(is_voted=True)
        return render(request,"myapp/home.html",context={"username":user})
    else:
        v=Voter.objects.get(user=u)
        candidates=Candidate.objects.filter(constituency=v.constituency)
    return render(request,"myapp/cast_vote.html",context={"candidates":candidates,"vote_status":v.is_voted})

def register(request):
    registered=False
    if request.method=="POST":
        userform=UserForm(request.POST)
        constform=VoterForm(request.POST)
        if userform.is_valid() and constform.is_valid():
            user=userform.save(commit=False)
            user.set_password(userform.cleaned_data['password'])
            user.save()
            profile=constform.save(commit=False)
            profile.user=user
            profile.save()
            registered=True
    userform=UserForm()
    constform=VoterForm()
    d={'registered':registered,'userform':userform,'constform':constform}
    return render(request,'register.html',context=d)


def user_login(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user and user.is_active:
            login(request,user)
            return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponse("Not a Active User or Invalid username and password")
    return render(request,'login.html',context={})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>
    {% block title %}BASE PAGE{% endblock %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar-expand-lg navbar-dark bg-dark">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:cast_vote' %}">Voting</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:registration' %}">Registration</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:login' %}">Login</a>
        </li>
        {% endif %}   
    </ul>   
</nav>
    {% block body_block %}
        
    {% endblock  %}
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}

{% block body_block %}
<br>
<div class="container">
   <div class="jumbotron">
        <form method="POST">
          {% csrf_token %}
          <label for="username">Username : </label>
          <input type="text" name="username" id="username">
          <label for="password">Password : </label>
          <input type="password" name="password" id="password">
          <input type="submit" value="Login" class="btn btn-primary">
        </form>
    </div>
  </div>
  
{% endblock %}

templates/myapp/cast_vote.html
{% extends "base.html" %}
{% block title %}
  <title>Voting Page</title>
{% endblock %}

{% block body_block %}
<br>
<div class="container">
{% if vote_status %}
<div class="jumbotron">
  <h1>You Have Already Casted the Vote</h1>
</div>
{% else %}
<div class="jumbotron">
  <h3>Select Candidate and Click on Vote</h3>
  <form method="POST">
      {% csrf_token %}
      {% if candidates %}
      Candidate_name : <select name="cand_name" id="cand_name">
        {% for candidate in candidates %}
        <option value="{{candidate}}">{{candidate}}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Vote">
      {% else %}
        <h1>No Candidates Are Contesting Election</h1>
      {% endif %}
  </form>
</div>
</div>
{% endif %}
{% endblock %}

templates/myapp/home.html
{% extends "base.html" %}
{% block title %}HOME{% endblock %}

{% block body_block %}
<br>
<div class="container">
  {% if username %}
  <div class="jumbotron">
    <h1>Welcome Mr./Ms.{{username}}</h1>
  </div>
  {% else %}
  <div class="container">
    <div class="jumbotron">
      <h2>Welcome to E Voting</h2>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}

{% block body_block %}
<br>
<div class="container">
    {% if registered %}
    <div class="container">
        <div class="jumbtron">
            <h1>Thanks For Registering</h1>
        </div>
    </div>
        
    {% else %}
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{userform|crispy}}
          {{constform|crispy}}
          <input type="submit" value="Register" class="btn btn-primary">
        </form>
    </div>
  </div>
    {% endif %}
    {% endblock %}